.PHONY: clean All

All:
	@echo "----------Building project:[ project38 - Debug ]----------"
	@cd "project38" && "$(MAKE)" -f  "project38.mk"
clean:
	@echo "----------Cleaning project:[ project38 - Debug ]----------"
	@cd "project38" && "$(MAKE)" -f  "project38.mk" clean
